# Generated by Django 4.2.1 on 2023-05-09 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sides', models.IntegerField()),
                ('material', models.CharField(max_length=30)),
                ('color', models.CharField(max_length=20)),
                ('text_color', models.CharField(max_length=20)),
            ],
        ),
    ]
