# Generated by Django 4.2.1 on 2023-05-09 01:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Dice',
            new_name='Die',
        ),
    ]
