# Generated by Django 4.2.1 on 2023-05-11 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_rename_dice_die'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rolls',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('result', models.PositiveIntegerField(choices=[('1', 'Nat 1 :('), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15'), ('16', '16'), ('17', '17'), ('18', '18'), ('19', '19'), ('20', 'Nat 20!')], default='1', max_length=2)),
                ('die', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.die')),
            ],
        ),
    ]
