# Generated by Django 4.2.1 on 2023-05-12 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_condition_alter_rolls_options_alter_rolls_result_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='die',
            old_name='chores',
            new_name='condition',
        ),
    ]
